linux_setup:
  hosts:
    rocky_group:
      hosts:
        rocky1:
          ansible_host: 10.0.5.10
          custom_device: ens34
          is_vyos: true
        rocky2:
          ansible_host: 10.0.5.11
          custom_device: ens34
          is_vyos: true
        rocky3:
          ansible_host: 10.0.5.12
          custom_device: ens34
          is_vyos: true
    ubuntu_group:
      hosts:
        dabuntumachine1:
          ansible_host: 10.0.5.30
          custom_device: ens33
          is_vyos: false
        dabuntumachine2:
          ansible_host: 10.0.5.31
          custom_device: ens33
          is_vyos: false
    impulse_group:
      hosts:
        impulse_machine:
          ansible_host: 10.0.5.30
          custom_device: ens33
          is_vyos: false
          is_impulse: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: vyos
    ansible_connection: network_cli
    ansible_network_os: vyos


