- name: Rocky Server Configuration  # Descriptive name for the playbook
  hosts: rocky
  tasks:
    - name: Ensure .ssh directory exists  # Task to ensure the existence of the .ssh directory
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: 0700

    - name: Ensure authorized_keys file exists  # Task to ensure the existence of the authorized_keys file
      file:
        path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        state: touch
        mode: 0644

    - name: Add SSH public key to authorized_keys  # Task to add SSH public key to authorized_keys
      blockinfile:
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        block: "{{ public_key }}"

    - name: Create sudoers drop-in file for user 480  # Task to create sudoers drop-in file for user 480
      file:
        path: /etc/sudoers.d/480
        state: touch
        mode: 0440
      become: yes

    - name: Add sudo permissions for user 480  # Task to add sudo permissions for user 480
      blockinfile:
        dest: /etc/sudoers.d/480
        block: "{{ ansible_user }}  ALL=(ALL) NOPASSWD: ALL"
      become: yes

    - name: Set hostname  # Task to set the hostname
      hostname:
        name: "{{ hostname }}"
      become: yes

    - name: Add hostname to hosts file  # Task to add hostname to hosts file
      lineinfile:
        path: /etc/hosts
        line: "127.0.1.1  {{ hostname }}"
      become: yes

    - name: Configure network settings with nmcli  # Task to configure network settings with nmcli
      nmcli:
        conn_name: "{{ device }}"
        ip4: "{{ lan_ip }}/24"
        gw4: "{{ gateway }}"
        state: present
        type: ethernet
        dns4:
          - "{{ name_server }}"
          - "{{ gateway }}"
        method4: manual
      become: yes

    - name: Restart the server  # Task to restart the server
      shell: "sleep 10 && shutdown -r"
      become: yes
      async: 1
      poll: 0


