- name: ubuntu playbook  # Descriptive name for the playbook
  hosts: ubuntu
  tasks:
    - name: Set Hostname  # Task to set the hostname
      hostname:
        name: "{{ hostname }}"
      become: yes

    - name: Add Host Entry  # Task to add hostname to hosts file
      lineinfile:
        path: /etc/hosts
        line: "127.0.1.1  {{ hostname }}"
      become: yes
  
    - name: Create .ssh Directory  # Task to create the .ssh directory
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: 0700

    - name: Ensure Authorized Keys File Existence  # Task to ensure the existence of the authorized_keys file
      file:
        path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        state: touch
        mode: 0644

    - name: Copy SSH Public Key to Authorized Keys  # Task to copy SSH public key to authorized_keys
      blockinfile:
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        block: "{{ public_key }}"

    - name: Create Sudoers Drop-in File  # Task to create sudoers drop-in file
      file:
        path: /etc/sudoers.d/480
        state: touch
        mode: 0440
      become: yes

    - name: Add Sudo Permissions for User  # Task to add sudo permissions for user
      blockinfile:
        dest: /etc/sudoers.d/480
        block: "{{ ansible_user }}  ALL=(ALL) NOPASSWD: ALL"
      become: yes

    - name: Load Netplan Config from Template  # Task to load netplan config from template
      become: yes
      template:
        src: 00-installer-config.yaml.j2
        dest: /etc/netplan/00-installer-config.yaml
        mode: "0644"
        owner: root
        group: root

    - name: Restart the Server  # Task to restart the server
      shell: "sleep 10 && shutdown -r"
      become: yes
      async: 1
      poll: 0



